/* ============================================================
   SANDMAN LYRA — Studio publishing engine
   Add, list, edit and delete posts. Each post belongs to a
   section (+ optional sub-tab) and shows on that page.
   Runs behind nginx Basic Auth; listens on 127.0.0.1 only.
   ============================================================ */
"use strict";
const express = require("express");
const multer = require("multer");
const fs = require("fs");
const path = require("path");

const WEBROOT = process.env.WEBROOT || "/var/www/sandmanlyra";
const PORT = process.env.PORT || 3000;
const DATA_DIR = path.join(WEBROOT, "assets", "data");
const IMG_DIR = path.join(WEBROOT, "assets", "images", "live");
const POSTS_FILE = path.join(DATA_DIR, "posts.json");
const FEED_JS = path.join(DATA_DIR, "feed-data.js");
const SECTIONS = ["live", "predictions", "journal", "library", "sports-mind", "culture", "media"];
const BET_STATUSES = ["pending", "won", "lost", "void"];

fs.mkdirSync(DATA_DIR, { recursive: true });
fs.mkdirSync(IMG_DIR, { recursive: true });

const storage = multer.diskStorage({
  destination: (req, file, cb) => cb(null, IMG_DIR),
  filename: (req, file, cb) => {
    let ext = path.extname(file.originalname || "").toLowerCase().replace(/[^.a-z0-9]/g, "");
    if (!ext) ext = (file.mimetype || "").indexOf("video") === 0 ? ".mp4" : ".jpg";
    cb(null, Date.now() + "-" + Math.random().toString(36).slice(2, 8) + ext);
  },
});
const ALLOWED = /^image\/(jpe?g|png|gif|webp)$|^video\/mp4$/;
const upload = multer({ storage, limits: { fileSize: 80 * 1024 * 1024 }, fileFilter: (req, file, cb) => cb(null, ALLOWED.test(file.mimetype || "")) });

function loadPosts() { try { return JSON.parse(fs.readFileSync(POSTS_FILE, "utf8")); } catch (e) { return []; } }
function savePosts(posts) {
  fs.writeFileSync(POSTS_FILE, JSON.stringify(posts, null, 2));
  fs.writeFileSync(FEED_JS, "/* Auto-generated by the Studio. Edit posts via the Studio, not by hand. */\nwindow.SANDMAN_POSTS = " + JSON.stringify(posts, null, 2) + ";\n");
}
function slugify(s) { return String(s || "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 40); }
function cleanCats(c) { return (Array.isArray(c) ? c : String(c || "").split(",")).map((x) => String(x).trim()).filter(Boolean); }
// Prediction / bet fields — power the track record & ROI ledger.
function applyBet(post, b) {
  function s(v, max) { return String(v == null ? "" : v).trim().slice(0, max || 200); }
  if ("event" in b) { const v = s(b.event, 120); if (v) post.event = v; else delete post.event; }
  if ("competition" in b) { const v = s(b.competition, 120); if (v) post.competition = v; else delete post.competition; }
  if ("pick" in b) { const v = s(b.pick, 200); if (v) post.pick = v; else delete post.pick; }
  if ("odds" in b) { const n = parseFloat(b.odds); if (!isNaN(n) && n > 0) post.odds = n; else delete post.odds; }
  if ("stake" in b) { const n = parseFloat(b.stake); if (!isNaN(n) && n >= 0) post.stake = n; else delete post.stake; }
  if ("status" in b) { const v = s(b.status, 12).toLowerCase(); post.status = BET_STATUSES.indexOf(v) !== -1 ? v : "pending"; }
  else if (post.section === "predictions" && !post.status) post.status = "pending";
}
function stripBet(post) { ["event", "competition", "pick", "odds", "stake", "status"].forEach((k) => delete post[k]); }
function applyMedia(post, file) {
  var rel = "assets/images/live/" + file.filename;
  if ((file.mimetype || "").indexOf("video") === 0) { post.type = "video"; post.video = rel; delete post.media; delete post.embed; }
  else { post.type = "photo"; post.media = rel; delete post.video; delete post.embed; }
}
function unlinkMedia(post) {
  [post.media, post.video].forEach(function (m) { if (m) { try { fs.unlinkSync(path.join(WEBROOT, m)); } catch (e) {} } });
}

try { savePosts(loadPosts()); } catch (e) {}

const app = express();
app.use(express.urlencoded({ extended: true }));
app.use(express.json());

app.get("/api/health", (req, res) => res.json({ ok: true, posts: loadPosts().length, sections: SECTIONS }));
app.get("/api/posts", (req, res) => res.json({ ok: true, posts: loadPosts() }));

app.post("/api/publish", (req, res) => {
  upload.single("media")(req, res, function (err) {
    if (err) return res.status(400).json({ ok: false, error: err.message });
    try {
      const b = req.body || {};
      const title = (b.title || "").trim(), caption = (b.caption || "").trim(), location = (b.location || "").trim(), embed = (b.embed || "").trim();
      let section = String(b.section || "live").trim(); if (SECTIONS.indexOf(section) === -1) section = "live";
      const subsection = (b.subsection || "").trim().slice(0, 60);
      const post = { id: "", date: "", section: section, type: "text", title: title, caption: caption, location: location, categories: cleanCats(b.categories) };
      if (subsection) post.subsection = subsection;
      if (req.file) applyMedia(post, req.file);
      if (embed) { post.type = "video"; post.embed = embed; }
      if (section === "predictions") applyBet(post, b);
      if (!title && !caption && !post.media && !post.video && !post.embed && !post.pick) return res.status(400).json({ ok: false, error: "Nothing to publish — add a caption, photo, video, or a pick." });
      const now = new Date();
      post.date = now.toISOString().slice(0, 10);
      post.id = post.date + "-" + section + "-" + (slugify(title) || Math.random().toString(36).slice(2, 7));
      const posts = loadPosts(); posts.unshift(post); savePosts(posts);
      res.json({ ok: true, post: post, total: posts.length });
    } catch (e) { res.status(500).json({ ok: false, error: String((e && e.message) || e) }); }
  });
});

app.post("/api/update", (req, res) => {
  upload.single("media")(req, res, function (err) {
    if (err) return res.status(400).json({ ok: false, error: err.message });
    try {
      const b = req.body || {};
      const id = (b.id || "").trim();
      const posts = loadPosts();
      const i = posts.findIndex(function (p) { return p.id === id; });
      if (i < 0) return res.status(404).json({ ok: false, error: "Post not found." });
      const post = posts[i];
      if ("title" in b) post.title = String(b.title || "").trim();
      if ("caption" in b) post.caption = String(b.caption || "").trim();
      if ("location" in b) post.location = String(b.location || "").trim();
      if ("section" in b) { let s = String(b.section || "live").trim(); if (SECTIONS.indexOf(s) !== -1) post.section = s; }
      if ("subsection" in b) { const sub = String(b.subsection || "").trim().slice(0, 60); if (sub) post.subsection = sub; else delete post.subsection; }
      if ("categories" in b) post.categories = cleanCats(b.categories);
      if (b.removeMedia === "1") { unlinkMedia(post); delete post.media; delete post.video; delete post.embed; post.type = "text"; }
      if ("embed" in b && (b.embed || "").trim()) { unlinkMedia(post); delete post.media; delete post.video; post.type = "video"; post.embed = b.embed.trim(); }
      if (req.file) { unlinkMedia(post); applyMedia(post, req.file); }
      if (post.section === "predictions") applyBet(post, b);
      else stripBet(post);
      savePosts(posts);
      res.json({ ok: true, post: post });
    } catch (e) { res.status(500).json({ ok: false, error: String((e && e.message) || e) }); }
  });
});

app.post("/api/delete", (req, res) => {
  try {
    const id = (req.body.id || "").trim();
    const posts = loadPosts();
    const i = posts.findIndex(function (p) { return p.id === id; });
    if (i < 0) return res.status(404).json({ ok: false, error: "Post not found." });
    const removed = posts.splice(i, 1)[0];
    unlinkMedia(removed);
    savePosts(posts);
    res.json({ ok: true, total: posts.length });
  } catch (e) { res.status(500).json({ ok: false, error: String((e && e.message) || e) }); }
});

app.listen(PORT, "127.0.0.1", () => console.log("Sandman Studio engine listening on 127.0.0.1:" + PORT));
