/* ============================================================
   SANDMAN LYRA — Studio publishing engine
   Receives a post from the Studio form (text + optional photo/
   video/embed), saves the media, and adds the post to the Live
   feed — so it appears on the site automatically.

   Runs behind nginx Basic Auth (only the logged-in owner reaches it).
   Listens on 127.0.0.1 only; nginx proxies /api/ to it.
   ============================================================ */
"use strict";
const express = require("express");
const multer = require("multer");
const fs = require("fs");
const path = require("path");

const WEBROOT = process.env.WEBROOT || "/var/www/sandmanlyra";
const PORT = process.env.PORT || 3000;
const DATA_DIR = path.join(WEBROOT, "assets", "data");
const IMG_DIR = path.join(WEBROOT, "assets", "images", "live");
const JSON_FILE = path.join(DATA_DIR, "live.json");
const JS_FILE = path.join(DATA_DIR, "live-data.js");

fs.mkdirSync(DATA_DIR, { recursive: true });
fs.mkdirSync(IMG_DIR, { recursive: true });

const storage = multer.diskStorage({
  destination: (req, file, cb) => cb(null, IMG_DIR),
  filename: (req, file, cb) => {
    let ext = path.extname(file.originalname || "").toLowerCase().replace(/[^.a-z0-9]/g, "");
    if (!ext) ext = (file.mimetype || "").indexOf("video") === 0 ? ".mp4" : ".jpg";
    cb(null, Date.now() + "-" + Math.random().toString(36).slice(2, 8) + ext);
  },
});
const ALLOWED = /^image\/(jpe?g|png|gif|webp)$|^video\/mp4$/;
const upload = multer({
  storage,
  limits: { fileSize: 80 * 1024 * 1024 }, // 80 MB
  fileFilter: (req, file, cb) => cb(null, ALLOWED.test(file.mimetype || "")),
});

function loadPosts() {
  try { return JSON.parse(fs.readFileSync(JSON_FILE, "utf8")); }
  catch (e) { return []; }
}
function savePosts(posts) {
  fs.writeFileSync(JSON_FILE, JSON.stringify(posts, null, 2));
  fs.writeFileSync(
    JS_FILE,
    "/* Auto-generated by the Studio publishing engine. Edit posts via the Studio, not by hand. */\n" +
      "window.SANDMAN_LIVE = " + JSON.stringify(posts, null, 2) + ";\n"
  );
}
function slugify(s) {
  return String(s || "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 40);
}

const app = express();
app.use(express.urlencoded({ extended: true }));

app.get("/api/health", (req, res) => res.json({ ok: true, posts: loadPosts().length }));

app.post("/api/publish", (req, res) => {
  upload.single("media")(req, res, function (err) {
    if (err) return res.status(400).json({ ok: false, error: err.message });
    try {
      const b = req.body || {};
      const title = (b.title || "").trim();
      const caption = (b.caption || "").trim();
      const location = (b.location || "").trim();
      const embed = (b.embed || "").trim();
      let cats = b.categories;
      cats = (Array.isArray(cats) ? cats : String(cats || "").split(","))
        .map((c) => String(c).trim()).filter(Boolean);

      const post = {
        id: "", date: "", type: "text",
        title, caption, location, categories: cats,
      };

      if (req.file) {
        const rel = "assets/images/live/" + req.file.filename;
        if ((req.file.mimetype || "").indexOf("video") === 0) { post.type = "video"; post.video = rel; }
        else { post.type = "photo"; post.media = rel; }
      }
      if (embed) { post.type = "video"; post.embed = embed; }

      if (!title && !caption && !post.media && !post.video && !post.embed) {
        return res.status(400).json({ ok: false, error: "Nothing to publish — add a caption, photo, or video." });
      }

      const now = new Date();
      post.date = now.toISOString().slice(0, 10);
      post.id = post.date + "-" + (slugify(title) || Math.random().toString(36).slice(2, 7));

      const posts = loadPosts();
      posts.unshift(post);
      savePosts(posts);
      res.json({ ok: true, post: post, total: posts.length });
    } catch (e) {
      res.status(500).json({ ok: false, error: String((e && e.message) || e) });
    }
  });
});

app.listen(PORT, "127.0.0.1", () => console.log("Sandman Studio engine listening on 127.0.0.1:" + PORT));
