/* ============================================================
   SANDMAN LYRA — Studio publishing engine
   Receives a post from the Studio (text + optional photo/video/
   embed) and a chosen SECTION, saves the media, and adds the post
   to that section's feed — so it appears on the right page of the
   site automatically.

   Runs behind nginx Basic Auth; listens on 127.0.0.1 only.
   ============================================================ */
"use strict";
const express = require("express");
const multer = require("multer");
const fs = require("fs");
const path = require("path");

const WEBROOT = process.env.WEBROOT || "/var/www/sandmanlyra";
const PORT = process.env.PORT || 3000;
const DATA_DIR = path.join(WEBROOT, "assets", "data");
const IMG_DIR = path.join(WEBROOT, "assets", "images", "live");
const POSTS_FILE = path.join(DATA_DIR, "posts.json");
const FEED_JS = path.join(DATA_DIR, "feed-data.js");

// Where a post can be published. Must match the site's pages + Studio dropdown.
const SECTIONS = ["live", "journal", "library", "sports-mind", "culture", "media"];

fs.mkdirSync(DATA_DIR, { recursive: true });
fs.mkdirSync(IMG_DIR, { recursive: true });

const storage = multer.diskStorage({
  destination: (req, file, cb) => cb(null, IMG_DIR),
  filename: (req, file, cb) => {
    let ext = path.extname(file.originalname || "").toLowerCase().replace(/[^.a-z0-9]/g, "");
    if (!ext) ext = (file.mimetype || "").indexOf("video") === 0 ? ".mp4" : ".jpg";
    cb(null, Date.now() + "-" + Math.random().toString(36).slice(2, 8) + ext);
  },
});
const ALLOWED = /^image\/(jpe?g|png|gif|webp)$|^video\/mp4$/;
const upload = multer({
  storage,
  limits: { fileSize: 80 * 1024 * 1024 },
  fileFilter: (req, file, cb) => cb(null, ALLOWED.test(file.mimetype || "")),
});

function loadPosts() {
  try { return JSON.parse(fs.readFileSync(POSTS_FILE, "utf8")); }
  catch (e) { return []; }
}
function savePosts(posts) {
  fs.writeFileSync(POSTS_FILE, JSON.stringify(posts, null, 2));
  fs.writeFileSync(
    FEED_JS,
    "/* Auto-generated by the Studio publishing engine. Edit posts via the Studio, not by hand. */\n" +
      "window.SANDMAN_POSTS = " + JSON.stringify(posts, null, 2) + ";\n"
  );
}
function slugify(s) {
  return String(s || "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 40);
}

// keep feed-data.js in sync with posts.json on every start (e.g. after a deploy)
try { savePosts(loadPosts()); } catch (e) { /* ignore */ }

const app = express();
app.use(express.urlencoded({ extended: true }));

app.get("/api/health", (req, res) => res.json({ ok: true, posts: loadPosts().length, sections: SECTIONS }));

app.post("/api/publish", (req, res) => {
  upload.single("media")(req, res, function (err) {
    if (err) return res.status(400).json({ ok: false, error: err.message });
    try {
      const b = req.body || {};
      const title = (b.title || "").trim();
      const caption = (b.caption || "").trim();
      const location = (b.location || "").trim();
      const embed = (b.embed || "").trim();
      let section = String(b.section || "live").trim();
      if (SECTIONS.indexOf(section) === -1) section = "live";
      const subsection = (b.subsection || "").trim().slice(0, 60);
      let cats = b.categories;
      cats = (Array.isArray(cats) ? cats : String(cats || "").split(","))
        .map((c) => String(c).trim()).filter(Boolean);

      const post = { id: "", date: "", section: section, type: "text",
        title: title, caption: caption, location: location, categories: cats };
      if (subsection) post.subsection = subsection;

      if (req.file) {
        const rel = "assets/images/live/" + req.file.filename;
        if ((req.file.mimetype || "").indexOf("video") === 0) { post.type = "video"; post.video = rel; }
        else { post.type = "photo"; post.media = rel; }
      }
      if (embed) { post.type = "video"; post.embed = embed; }

      if (!title && !caption && !post.media && !post.video && !post.embed) {
        return res.status(400).json({ ok: false, error: "Nothing to publish — add a caption, photo, or video." });
      }

      const now = new Date();
      post.date = now.toISOString().slice(0, 10);
      post.id = post.date + "-" + section + "-" + (slugify(title) || Math.random().toString(36).slice(2, 7));

      const posts = loadPosts();
      posts.unshift(post);
      savePosts(posts);
      res.json({ ok: true, post: post, total: posts.length });
    } catch (e) {
      res.status(500).json({ ok: false, error: String((e && e.message) || e) });
    }
  });
});

app.listen(PORT, "127.0.0.1", () => console.log("Sandman Studio engine listening on 127.0.0.1:" + PORT));
